import type { Request, Response } from "express";
import fs from "fs";
import path from "path";

function readGatewayToken(): string | null {
  // Prefer explicit env override
  const envToken = process.env.CLAWDBOT_GATEWAY_TOKEN;
  if (envToken) return envToken;

  // Project-local gateway token generated by agent/run-gateway.sh
  const tokenPath = path.join(process.cwd(), "agent", ".clawdbot-state", "gateway-token");
  try {
    const t = fs.readFileSync(tokenPath, "utf8").trim();
    return t || null;
  } catch {
    return null;
  }
}

function normalizeIp(raw: string | undefined): string {
  if (!raw) return "";
  if (raw === "::1") return "127.0.0.1";
  if (raw.startsWith("::ffff:")) return raw.slice(7);
  return raw;
}

function isTrustedRemote(rawIp: string | undefined): boolean {
  if (process.env.CLAWDBOT_TOKEN_ALLOW_ANY === "1") return true;

  const ip = normalizeIp(rawIp);
  if (!ip) return false;
  if (ip === "127.0.0.1") return true;

  if (ip.startsWith("10.")) return true;
  if (ip.startsWith("192.168.")) return true;
  if (ip.startsWith("172.")) {
    const parts = ip.split(".");
    if (parts.length >= 2) {
      const second = Number(parts[1]);
      if (!Number.isNaN(second) && second >= 16 && second <= 31) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Local-only helper to let the embedded /bot page pass the gateway token into
 * the Control UI URL.
 *
 * This avoids the common 1006 handshake timeout when the UI is served from a
 * different origin (localhost:5000) than the gateway (localhost:29789) and the
 * token isn't yet stored in that origin's localStorage.
 */
export function clawdbotTokenHandler(req: Request, res: Response) {
  const rawIp = req.socket.remoteAddress;
  if (!isTrustedRemote(rawIp)) {
    return res.status(403).json({ ok: false, error: "Forbidden" });
  }

  const token = readGatewayToken();
  if (!token) return res.status(404).json({ ok: false, error: "Gateway token not found" });

  return res.json({ ok: true, token });
}
