import type { Request, Response } from "express";
import fs from "fs";
import path from "path";

function readGatewayToken(): string | null {
  // Prefer explicit env override
  const envToken = process.env.CLAWDBOT_GATEWAY_TOKEN;
  if (envToken) return envToken;

  // Project-local gateway token generated by agent/run-gateway.sh
  const tokenPath = path.join(process.cwd(), "agent", ".clawdbot-state", "gateway-token");
  try {
    const t = fs.readFileSync(tokenPath, "utf8").trim();
    return t || null;
  } catch {
    return null;
  }
}

/**
 * Local-only helper to let the embedded /bot page pass the gateway token into
 * the Control UI URL.
 *
 * This avoids the common 1006 handshake timeout when the UI is served from a
 * different origin (localhost:5000) than the gateway (localhost:29789) and the
 * token isn't yet stored in that origin's localStorage.
 */
export function clawdbotTokenHandler(req: Request, res: Response) {
  // Only allow loopback access.
  const ip = req.socket.remoteAddress || "";
  if (!(ip === "127.0.0.1" || ip === "::1" || ip.endsWith("::ffff:127.0.0.1"))) {
    return res.status(403).json({ ok: false, error: "Forbidden" });
  }

  const token = readGatewayToken();
  if (!token) return res.status(404).json({ ok: false, error: "Gateway token not found" });

  return res.json({ ok: true, token });
}
