import { sql } from "drizzle-orm";
import {
  sqliteTable,
  text,
  integer,
  real,
} from "drizzle-orm/sqlite-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// SQLite-friendly IDs.
// We use a stable random hex string generated by SQLite (unique enough for local use).
const idDefault = sql`(lower(hex(randomblob(16))))`;

export const users = sqliteTable("users", {
  id: text("id").primaryKey().default(idDefault),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
});

export const uploadedFiles = sqliteTable("uploaded_files", {
  id: text("id").primaryKey().default(idDefault),
  filename: text("filename").notNull(),
  originalName: text("original_name").notNull(),
  filePath: text("file_path").notNull(),
  fileType: text("file_type").notNull(),
  mimeType: text("mime_type").notNull(),
  // Optional stable identifier for PDFs (sha256 of file bytes)
  pdfId: text("pdf_id"),
  uploadedAt: integer("uploaded_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const trainingSessions = sqliteTable("training_sessions", {
  id: text("id").primaryKey().default(idDefault),
  name: text("name").notNull(),
  // Legacy key
  pdfPath: text("pdf_path").notNull(),
  // Stable key (sha256 of PDF bytes)
  pdfId: text("pdf_id"),
  audioPath: text("audio_path"),
  status: text("status").notNull().default("pending"),
  totalPages: integer("total_pages").notNull().default(1),
  sampleRate: integer("sample_rate").default(44100),
  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const pageMarkers = sqliteTable("page_markers", {
  id: text("id").primaryKey().default(idDefault),
  sessionId: text("session_id")
    .notNull()
    .references(() => trainingSessions.id, { onDelete: "cascade" }),

  // Stable keys for cross-PDF reuse
  pdfId: text("pdf_id"),
  pageId: text("page_id"),

  pageNumber: integer("page_number").notNull(),
  timestampMs: integer("timestamp_ms").notNull(),

  // JSON blobs stored as text (SQLite)
  audioFeatures: text("audio_features", { mode: "json" }).$type<any>(),

  // Stored as JSON array of strings in SQLite
  triggerTokens: text("trigger_tokens", { mode: "json" }).$type<any>(),
  triggerConfidence: real("trigger_confidence"),

  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const aggregatedFingerprints = sqliteTable("aggregated_fingerprints", {
  id: text("id").primaryKey().default(idDefault),

  // Legacy key
  pdfPath: text("pdf_path").notNull(),

  // Stable keys
  pdfId: text("pdf_id"),
  pageId: text("page_id"),

  pageNumber: integer("page_number").notNull(),
  sessionCount: integer("session_count").notNull().default(1),
  averageTimestampMs: integer("average_timestamp_ms").notNull(),

  averagedFeatures: text("averaged_features", { mode: "json" }).$type<any>(),
  featureHistory: text("feature_history", { mode: "json" }).$type<any>(),

  confidence: real("confidence").default(0),
  updatedAt: integer("updated_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const pageTranscripts = sqliteTable("page_transcripts", {
  id: text("id").primaryKey().default(idDefault),

  // Legacy key
  pdfPath: text("pdf_path").notNull(),

  // Stable keys
  pdfId: text("pdf_id"),
  pageId: text("page_id"),

  pageNumber: integer("page_number").notNull(),
  transcript: text("transcript").notNull(),

  // Stored as JSON array of strings in SQLite
  keywords: text("keywords", { mode: "json" }).$type<any>(),

  sessionCount: integer("session_count").notNull().default(1),
  updatedAt: integer("updated_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

// Word dictionary for Armenian ↔ Phonetic mapping
export const wordDictionary = sqliteTable("word_dictionary", {
  id: text("id").primaryKey().default(idDefault),
  pdfId: text("pdf_id").notNull(),
  armenian: text("armenian").notNull(),
  phonetic: text("phonetic").notNull(),
  pageNumber: integer("page_number"),
  occurrences: integer("occurrences").notNull().default(1),
  confidence: real("confidence").default(1.0),
  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

// Page sections - stores Armenian, Phonetic, English separately per page
export const pageSections = sqliteTable("page_sections", {
  id: text("id").primaryKey().default(idDefault),
  pdfId: text("pdf_id").notNull(),
  pageNumber: integer("page_number").notNull(),
  armenianText: text("armenian_text"),
  phoneticText: text("phonetic_text"),
  englishText: text("english_text"),
  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

// Stores each learning attempt separately for comparison
export const learningAttempts = sqliteTable("learning_attempts", {
  id: text("id").primaryKey().default(idDefault),

  // Legacy key
  pdfPath: text("pdf_path").notNull(),

  // Stable key (sha256 of PDF bytes)
  pdfId: text("pdf_id"),

  audioPath: text("audio_path").notNull(),
  name: text("name"),
  status: text("status").notNull().default("completed"),
  pagesProcessed: integer("pages_processed").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

// Stores transcription results for each page in a learning attempt
export const learningAttemptPages = sqliteTable("learning_attempt_pages", {
  id: text("id").primaryKey().default(idDefault),
  attemptId: text("attempt_id")
    .notNull()
    .references(() => learningAttempts.id, { onDelete: "cascade" }),
  pageNumber: integer("page_number").notNull(),
  transcript: text("transcript").notNull(),
  duration: real("duration"),
  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

// --- Zod schemas ---

export const insertPageTranscriptSchema = createInsertSchema(pageTranscripts, {
  keywords: z.any().optional(),
}).omit({
  id: true,
  updatedAt: true,
});

export const insertWordDictionarySchema = createInsertSchema(wordDictionary).omit({
  id: true,
  createdAt: true,
});

export const insertPageSectionsSchema = createInsertSchema(pageSections).omit({
  id: true,
  createdAt: true,
});

export const insertLearningAttemptSchema = createInsertSchema(learningAttempts).omit({
  id: true,
  createdAt: true,
});

export const insertLearningAttemptPageSchema = createInsertSchema(learningAttemptPages).omit({
  id: true,
  createdAt: true,
});

export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
});

export const insertFileSchema = createInsertSchema(uploadedFiles).omit({
  id: true,
  uploadedAt: true,
});

export const insertTrainingSessionSchema = createInsertSchema(trainingSessions).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertPageMarkerSchema = createInsertSchema(pageMarkers, {
  audioFeatures: z.any().optional(),
  triggerTokens: z.any().optional(),
}).omit({
  id: true,
  createdAt: true,
});

export const insertAggregatedFingerprintSchema = createInsertSchema(aggregatedFingerprints, {
  averagedFeatures: z.any().optional(),
  featureHistory: z.any().optional(),
}).omit({
  id: true,
  updatedAt: true,
});

// Types
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type UploadedFile = typeof uploadedFiles.$inferSelect;
export type InsertFile = z.infer<typeof insertFileSchema>;
export type TrainingSession = typeof trainingSessions.$inferSelect;
export type InsertTrainingSession = z.infer<typeof insertTrainingSessionSchema>;
export type PageMarker = typeof pageMarkers.$inferSelect;
export type InsertPageMarker = z.infer<typeof insertPageMarkerSchema>;
export type AggregatedFingerprint = typeof aggregatedFingerprints.$inferSelect;
export type InsertAggregatedFingerprint = z.infer<typeof insertAggregatedFingerprintSchema>;
export type PageTranscript = typeof pageTranscripts.$inferSelect;
export type InsertPageTranscript = z.infer<typeof insertPageTranscriptSchema>;
export type LearningAttempt = typeof learningAttempts.$inferSelect;
export type InsertLearningAttempt = z.infer<typeof insertLearningAttemptSchema>;
export type LearningAttemptPage = typeof learningAttemptPages.$inferSelect;
export type InsertLearningAttemptPage = z.infer<typeof insertLearningAttemptPageSchema>;
export type WordDictionary = typeof wordDictionary.$inferSelect;
export type InsertWordDictionary = z.infer<typeof insertWordDictionarySchema>;
export type PageSections = typeof pageSections.$inferSelect;

// Local Chat (replaces Telegram)
export const conversations = sqliteTable("conversations", {
  id: text("id").primaryKey().default(idDefault),
  title: text("title").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const messages = sqliteTable("messages", {
  id: text("id").primaryKey().default(idDefault),
  conversationId: text("conversation_id")
    .notNull()
    .references(() => conversations.id, { onDelete: "cascade" }),
  role: text("role").notNull(), // "user" or "assistant"
  content: text("content").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const insertConversationSchema = createInsertSchema(conversations).omit({
  id: true,
  createdAt: true,
});

export const insertMessageSchema = createInsertSchema(messages).omit({
  id: true,
  createdAt: true,
});

export type Conversation = typeof conversations.$inferSelect;
export type InsertConversation = z.infer<typeof insertConversationSchema>;
export type Message = typeof messages.$inferSelect;
export type InsertMessage = z.infer<typeof insertMessageSchema>;

// Self-Improvement Metrics
export const improvementMetrics = sqliteTable("improvement_metrics", {
  id: text("id").primaryKey().default(idDefault),
  testDate: text("test_date").notNull(),
  testType: text("test_type").notNull(), // 'live_service' or 'self_test'
  audioFile: text("audio_file"),
  totalPages: integer("total_pages").notNull(),
  correctTurns: integer("correct_turns").notNull(),
  missedTurns: integer("missed_turns").notNull(),
  falsePositives: integer("false_positives").notNull(),
  accuracyPercentage: real("accuracy_percentage").notNull(),
  averageLatencyMs: integer("average_latency_ms"),
  averageConfidence: real("average_confidence"),
  notes: text("notes"),
  improvements: text("improvements", { mode: "json" }).$type<string[]>(),
  issues: text("issues", { mode: "json" }).$type<string[]>(),
  createdAt: integer("created_at", { mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const insertImprovementMetricSchema = createInsertSchema(improvementMetrics, {
  improvements: z.any().optional(),
  issues: z.any().optional(),
}).omit({
  id: true,
  createdAt: true,
});

export type ImprovementMetric = typeof improvementMetrics.$inferSelect;
export type InsertImprovementMetric = z.infer<typeof insertImprovementMetricSchema>;
